export type Product = {
  id: string;
  name: string;
  category: string;
  price: number;
  blurb: string;
  image?: string;
};

export const products: Product[] = [
  // ── iPhone ──────────────────────────────────────────────
  {
    id: "iphone-15-pro",
    name: "iPhone 15 Pro",
    category: "phones",
    price: 1199,
    blurb: "Titanium. So strong. So light. So Pro.",
    image: "/products/iphone-15-pro.png",
  },
  {
    id: "iphone-15-pro-max",
    name: "iPhone 15 Pro Max",
    category: "phones",
    price: 1499,
    blurb: "The longest optical zoom on iPhone, ever.",
    image: "/products/iphone-15-pro-max.png",
  },
  {
    id: "iphone-15",
    name: "iPhone 15",
    category: "phones",
    price: 899,
    blurb: "Newphoria. With the Dynamic Island and 48MP camera.",
    image: "/products/iphone-15.png",
  },
  {
    id: "iphone-15-plus",
    name: "iPhone 15 Plus",
    category: "phones",
    price: 999,
    blurb: "Bigger screen. Bigger battery. Newphoria.",
    image: "/products/iphone-15-plus.png",
  },
  {
    id: "iphone-14",
    name: "iPhone 14",
    category: "phones",
    price: 699,
    blurb: "Big and bigger. Now with Crash Detection.",
    image: "/products/iphone-14.png",
  },
  {
    id: "iphone-13",
    name: "iPhone 13",
    category: "phones",
    price: 599,
    blurb: "A total powerhouse. Beloved A15 Bionic chip.",
    image: "/products/iphone-13.png",
  },
  {
    id: "iphone-se-3",
    name: "iPhone SE",
    category: "phones",
    price: 429,
    blurb: "Serious power. Serious value. Touch ID returns.",
    image: "/products/iphone-se-3.png",
  },

  // ── iPad ────────────────────────────────────────────────
  {
    id: "ipad",
    name: "iPad",
    category: "tablets",
    price: 449,
    blurb: "Lovable. Drawable. Magical.",
    image: "/products/ipad.png",
  },
  {
    id: "ipad-air",
    name: "iPad Air",
    category: "tablets",
    price: 599,
    blurb: "Serious performance in a light, colorful design.",
    image: "/products/ipad-air.png",
  },
  {
    id: "ipad-pro-11",
    name: 'iPad Pro 11"',
    category: "tablets",
    price: 999,
    blurb: "M4 chip. Ultra Retina XDR. Impossibly thin.",
    image: "/products/ipad-pro-11.png",
  },
  {
    id: "ipad-pro-13",
    name: 'iPad Pro 13"',
    category: "tablets",
    price: 1299,
    blurb: "The thinnest Apple product ever made.",
    image: "/products/ipad-pro-13.png",
  },
  {
    id: "ipad-mini",
    name: "iPad mini",
    category: "tablets",
    price: 499,
    blurb: "Mega power. Mini sized.",
    image: "/products/ipad-mini.png",
  },

  // ── Mac ─────────────────────────────────────────────────
  {
    id: "macbook-air",
    name: "MacBook Air",
    category: "laptops",
    price: 999,
    blurb: "Lean. Mean. M3 machine.",
    image: "/products/macbook-air.png",
  },
  {
    id: "macbook-air-15",
    name: 'MacBook Air 15"',
    category: "laptops",
    price: 1299,
    blurb: "Impossibly thin, with a big, beautiful display.",
    image: "/products/macbook-air-15.png",
  },
  {
    id: "macbook-pro-14",
    name: 'MacBook Pro 14"',
    category: "laptops",
    price: 1599,
    blurb: "Built for Apple Intelligence. Ridiculously fast.",
    image: "/products/macbook-pro-14.png",
  },
  {
    id: "macbook-pro-16",
    name: 'MacBook Pro 16"',
    category: "laptops",
    price: 2499,
    blurb: "M3 Max. The most powerful MacBook ever.",
    image: "/products/macbook-pro-16.png",
  },
  {
    id: "imac",
    name: "iMac",
    category: "desktops",
    price: 1299,
    blurb: "Hello (again).",
    image: "/products/imac.png",
  },
  {
    id: "mac-mini",
    name: "Mac mini",
    category: "desktops",
    price: 599,
    blurb: "Big things, small package. Now with M2 Pro.",
    image: "/products/mac-mini.png",
  },
  {
    id: "mac-studio",
    name: "Mac Studio",
    category: "desktops",
    price: 1999,
    blurb: "Empowers pros to build studios of their own.",
    image: "/products/mac-studio.png",
  },
  {
    id: "mac-pro",
    name: "Mac Pro",
    category: "desktops",
    price: 6999,
    blurb: "Tower of power. M2 Ultra inside.",
    image: "/products/mac-pro.png",
  },

  // ── Apple Watch ────────────────────────────────────────
  {
    id: "apple-watch",
    name: "Apple Watch Ultra 2",
    category: "watches",
    price: 799,
    blurb: "The most rugged Apple Watch.",
    image: "/products/apple-watch.png",
  },
  {
    id: "apple-watch-9",
    name: "Apple Watch Series 9",
    category: "watches",
    price: 399,
    blurb: "Smarter. Brighter. Mightier.",
    image: "/products/apple-watch-9.png",
  },
  {
    id: "apple-watch-se",
    name: "Apple Watch SE",
    category: "watches",
    price: 249,
    blurb: "All the essentials. Heart of Apple Watch.",
    image: "/products/apple-watch-se.png",
  },
  {
    id: "apple-watch-hermes",
    name: "Apple Watch Hermès",
    category: "watches",
    price: 1249,
    blurb: "Crafted in collaboration with Hermès.",
    image: "/products/apple-watch-hermes.png",
  },

  // ── AirPods & Audio ────────────────────────────────────
  {
    id: "airpods",
    name: "AirPods Pro",
    category: "audio",
    price: 249,
    blurb: "Adaptive Audio. Now playing.",
    image: "/products/airpods.png",
  },
  {
    id: "airpods-3",
    name: "AirPods (3rd generation)",
    category: "audio",
    price: 169,
    blurb: "All-new contoured design. Spatial Audio.",
    image: "/products/airpods-3.png",
  },
  {
    id: "airpods-max",
    name: "AirPods Max",
    category: "audio",
    price: 549,
    blurb: "A perfect balance of exhilarating sound.",
    image: "/products/airpods-max.png",
  },
  {
    id: "beats-studio-pro",
    name: "Beats Studio Pro",
    category: "audio",
    price: 349,
    blurb: "Custom acoustic platform. Lossless audio via USB-C.",
    image: "/products/beats-studio-pro.png",
  },
  {
    id: "beats-fit-pro",
    name: "Beats Fit Pro",
    category: "audio",
    price: 199,
    blurb: "Built for movement. Active Noise Cancelling.",
    image: "/products/beats-fit-pro.png",
  },

  // ── TV & Home ──────────────────────────────────────────
  {
    id: "apple-tv-4k",
    name: "Apple TV 4K",
    category: "tv-home",
    price: 129,
    blurb: "The Apple experience. Cinematic in every sense.",
    image: "/products/apple-tv-4k.png",
  },
  {
    id: "homepod",
    name: "HomePod (2nd generation)",
    category: "tv-home",
    price: 299,
    blurb: "Profound sound. Comes with Siri.",
    image: "/products/homepod.png",
  },
  {
    id: "homepod-mini",
    name: "HomePod mini",
    category: "tv-home",
    price: 99,
    blurb: "Room-filling sound. Intelligent assistant. Smart-home hub.",
    image: "/products/homepod-mini.png",
  },
  {
    id: "vision-pro",
    name: "Apple Vision Pro",
    category: "spatial",
    price: 3499,
    blurb: "Welcome to the era of spatial computing.",
    image: "/products/vision-pro.png",
  },

  // ── Displays ───────────────────────────────────────────
  {
    id: "studio-display",
    name: "Studio Display",
    category: "displays",
    price: 1599,
    blurb: '27" 5K Retina. Best-in-class camera and audio.',
    image: "/products/studio-display.png",
  },
  {
    id: "pro-display-xdr",
    name: "Pro Display XDR",
    category: "displays",
    price: 4999,
    blurb: "Workflow workhorse with extreme dynamic range.",
    image: "/products/pro-display-xdr.png",
  },

  // ── Accessories ────────────────────────────────────────
  {
    id: "magic-keyboard",
    name: "Magic Keyboard",
    category: "accessories",
    price: 129,
    blurb: "Refined precision and a built-in rechargeable battery.",
    image: "/products/magic-keyboard.png",
  },
  {
    id: "magic-mouse",
    name: "Magic Mouse",
    category: "accessories",
    price: 99,
    blurb: "Multi-Touch surface, sleek design, USB-C.",
    image: "/products/magic-mouse.png",
  },
  {
    id: "magic-trackpad",
    name: "Magic Trackpad",
    category: "accessories",
    price: 129,
    blurb: "Edge-to-edge glass. Force Touch.",
    image: "/products/magic-trackpad.png",
  },
  {
    id: "apple-pencil-pro",
    name: "Apple Pencil Pro",
    category: "accessories",
    price: 129,
    blurb: "Squeeze, roll, barrel roll, haptic feedback.",
    image: "/products/apple-pencil-pro.png",
  },
  {
    id: "apple-pencil-usbc",
    name: "Apple Pencil (USB-C)",
    category: "accessories",
    price: 79,
    blurb: "Pixel-perfect precision at a great value.",
    image: "/products/apple-pencil-usbc.png",
  },
  {
    id: "magsafe-charger",
    name: "MagSafe Charger",
    category: "accessories",
    price: 39,
    blurb: "Faster wireless charging, perfectly aligned.",
    image: "/products/magsafe-charger.png",
  },
  {
    id: "usbc-20w",
    name: "20W USB-C Power Adapter",
    category: "accessories",
    price: 19,
    blurb: "Fast, efficient charging at home or in the office.",
    image: "/products/usbc-20w.png",
  },
  {
    id: "smart-folio",
    name: "Smart Folio for iPad Pro",
    category: "accessories",
    price: 79,
    blurb: "Lightweight protection that folds to your perfect viewing angle.",
    image: "/products/smart-folio.png",
  },

  // ── Cases & extras ─────────────────────────────────────
  {
    id: "iphone-silicone-case",
    name: "iPhone 15 Pro Silicone Case",
    category: "cases",
    price: 49,
    blurb: "Silky, soft-touch finish that feels great in your hand.",
    image: "/products/iphone-silicone-case.png",
  },
  {
    id: "iphone-finewoven-case",
    name: "iPhone 15 Pro FineWoven Case",
    category: "cases",
    price: 59,
    blurb: "Durable microtwill made from 68 percent post-consumer recycled content.",
    image: "/products/iphone-finewoven-case.png",
  },
  {
    id: "macbook-sleeve",
    name: 'Magic Sleeve for MacBook Pro 14"',
    category: "cases",
    price: 199,
    blurb: "Custom-fit, microfiber-lined protection.",
    image: "/products/macbook-sleeve.png",
  },
  {
    id: "finewoven-wallet",
    name: "FineWoven Wallet with MagSafe",
    category: "cases",
    price: 59,
    blurb: "Snap-on wallet with Find My support.",
    image: "/products/finewoven-wallet.png",
  },

  // ── Software / services ────────────────────────────────
  {
    id: "applecare-iphone",
    name: "AppleCare+ for iPhone",
    category: "services",
    price: 199,
    blurb: "Expert technical support and accidental damage cover.",
    image: "/products/applecare-iphone.png",
  },
  {
    id: "apple-one",
    name: "Apple One Gift Card",
    category: "services",
    price: 50,
    blurb: "Music, TV+, Arcade, iCloud+ — bundled in one card.",
    image: "/products/apple-one.png",
  },
  {
    id: "icloud-plus",
    name: "iCloud+ 2TB Plan",
    category: "services",
    price: 119,
    blurb: "Annual storage with Private Relay and Hide My Email.",
    image: "/products/icloud-plus.png",
  },
];

export function getProduct(id: string): Product | undefined {
  return products.find((p) => p.id === id);
}
