export type Product = {
  id: string;
  name: string;
  category: string;
  price: number;
  blurb: string;
  image?: string;
};

export const products: Product[] = [
  // ── Smart home ─────────────────────────────────────────
  {
    id: "echo-dot",
    name: "Echo Dot (5th Gen)",
    category: "smart-home",
    price: 49,
    blurb: "Compact smart speaker with bigger sound.",
    image: "/products/echo-dot.png",
  },
  {
    id: "echo-show-8",
    name: "Echo Show 8",
    category: "smart-home",
    price: 149,
    blurb: 'HD smart display with Alexa and 13MP camera.',
    image: "/products/echo-show-8.png",
  },
  {
    id: "ring-doorbell",
    name: "Ring Video Doorbell",
    category: "smart-home",
    price: 99,
    blurb: "1080p HD video, two-way talk, motion alerts.",
    image: "/products/ring-doorbell.png",
  },
  {
    id: "blink-outdoor",
    name: "Blink Outdoor 4 Camera",
    category: "smart-home",
    price: 119,
    blurb: "Wireless smart security camera with 2-year battery life.",
    image: "/products/blink-outdoor.png",
  },
  {
    id: "fire-tv-stick",
    name: "Fire TV Stick 4K Max",
    category: "smart-home",
    price: 59,
    blurb: "Most powerful Fire TV streaming stick. Wi-Fi 6E.",
    image: "/products/fire-tv-stick.png",
  },
  {
    id: "kasa-smart-plug",
    name: "Kasa Smart Plug 4-pack",
    category: "smart-home",
    price: 24,
    blurb: "Control devices from anywhere. No hub required.",
    image: "/products/kasa-smart-plug.png",
  },

  // ── Ebook readers & tablets ───────────────────────────
  {
    id: "kindle",
    name: "Kindle Paperwhite",
    category: "ebook-readers",
    price: 159,
    blurb: 'Glare-free 6.8" display, 10-week battery.',
    image: "/products/kindle.png",
  },
  {
    id: "kindle-scribe",
    name: "Kindle Scribe",
    category: "ebook-readers",
    price: 339,
    blurb: 'Read and write like paper. 10.2" display.',
    image: "/products/kindle-scribe.png",
  },
  {
    id: "kindle-oasis",
    name: "Kindle Oasis",
    category: "ebook-readers",
    price: 249,
    blurb: 'Premium 7" display with adjustable warm light.',
    image: "/products/kindle-oasis.png",
  },
  {
    id: "fire-hd-10",
    name: "Fire HD 10 Tablet",
    category: "tablets",
    price: 139,
    blurb: 'Octa-core processor, 10.1" 1080p display.',
    image: "/products/fire-hd-10.png",
  },

  // ── Audio ──────────────────────────────────────────────
  {
    id: "airpods-pro",
    name: "AirPods Pro (USB-C)",
    category: "audio",
    price: 229,
    blurb: "Active noise cancellation. Adaptive Audio.",
    image: "/products/airpods-pro.png",
  },
  {
    id: "wh-1000xm5",
    name: "Sony WH-1000XM5",
    category: "audio",
    price: 348,
    blurb: "Industry-leading noise cancellation.",
    image: "/products/wh-1000xm5.png",
  },
  {
    id: "bose-qc-ultra",
    name: "Bose QuietComfort Ultra",
    category: "audio",
    price: 429,
    blurb: "Immersive Audio. World-class noise cancellation.",
    image: "/products/bose-qc-ultra.png",
  },
  {
    id: "jbl-flip-6",
    name: "JBL Flip 6",
    category: "audio",
    price: 99,
    blurb: "Bold sound for every adventure. IP67 waterproof.",
    image: "/products/jbl-flip-6.png",
  },
  {
    id: "soundcore-liberty-4",
    name: "Anker Soundcore Liberty 4",
    category: "audio",
    price: 99,
    blurb: "ACAA 3.0 dual driver. Heart-rate monitor.",
    image: "/products/soundcore-liberty-4.png",
  },

  // ── Computer accessories ──────────────────────────────
  {
    id: "mx-master",
    name: "Logitech MX Master 3S",
    category: "accessories",
    price: 99,
    blurb: "Ergonomic, ultra-fast scrolling, quiet clicks.",
    image: "/products/mx-master.png",
  },
  {
    id: "mx-keys-s",
    name: "Logitech MX Keys S",
    category: "accessories",
    price: 119,
    blurb: "Smart illumination. Perfect-stroke keys.",
    image: "/products/mx-keys-s.png",
  },
  {
    id: "anker-65w",
    name: "Anker 65W GaN Charger",
    category: "accessories",
    price: 39,
    blurb: "Compact PD charger. Powers laptop, tablet, phone.",
    image: "/products/anker-65w.png",
  },
  {
    id: "sandisk-1tb-ssd",
    name: "SanDisk 1TB Extreme Portable SSD",
    category: "accessories",
    price: 89,
    blurb: "Up to 1050MB/s read. IP65 rated.",
    image: "/products/sandisk-1tb-ssd.png",
  },
  {
    id: "kingston-usb",
    name: "Kingston DataTraveler 256GB",
    category: "accessories",
    price: 19,
    blurb: "USB 3.2 thumb drive with sliding cap.",
    image: "/products/kingston-usb.png",
  },

  // ── Toys & games ──────────────────────────────────────
  {
    id: "lego-millennium-falcon",
    name: "LEGO Millennium Falcon",
    category: "toys",
    price: 169,
    blurb: "1,353 pieces. May the bricks be with you.",
    image: "/products/lego-millennium-falcon.png",
  },
  {
    id: "lego-x-wing",
    name: "LEGO Star Wars X-Wing Starfighter",
    category: "toys",
    price: 79,
    blurb: "Recreate Luke's flight from Yavin 4.",
    image: "/products/lego-x-wing.png",
  },
  {
    id: "switch-oled",
    name: "Nintendo Switch OLED",
    category: "games",
    price: 349,
    blurb: 'Vivid 7" OLED screen. Enhanced audio.',
    image: "/products/switch-oled.png",
  },
  {
    id: "ps5",
    name: "PlayStation 5 Slim",
    category: "games",
    price: 499,
    blurb: "Lightning-fast SSD. 4K gaming.",
    image: "/products/ps5.png",
  },
  {
    id: "xbox-series-x",
    name: "Xbox Series X",
    category: "games",
    price: 499,
    blurb: "12 teraflops of GPU power. True 4K.",
    image: "/products/xbox-series-x.png",
  },

  // ── Apparel ───────────────────────────────────────────
  {
    id: "levis-501",
    name: "Levi's 501 Original Jeans",
    category: "apparel",
    price: 69,
    blurb: "The blueprint of denim since 1873.",
    image: "/products/levis-501.png",
  },
  {
    id: "nike-dri-fit",
    name: "Nike Dri-FIT Tee",
    category: "apparel",
    price: 28,
    blurb: "Sweat-wicking fabric for everyday training.",
    image: "/products/nike-dri-fit.png",
  },
  {
    id: "patagonia-better-sweater",
    name: "Patagonia Better Sweater",
    category: "apparel",
    price: 149,
    blurb: "Recycled polyester fleece for cool-weather adventures.",
    image: "/products/patagonia-better-sweater.png",
  },
  {
    id: "carhartt-beanie",
    name: "Carhartt Acrylic Watch Hat",
    category: "apparel",
    price: 18,
    blurb: "The iconic ribbed knit beanie.",
    image: "/products/carhartt-beanie.png",
  },
  {
    id: "birkenstock-arizona",
    name: "Birkenstock Arizona",
    category: "apparel",
    price: 110,
    blurb: "The original two-strap sandal. Cork footbed.",
    image: "/products/birkenstock-arizona.png",
  },

  // ── Kitchen & dining ──────────────────────────────────
  {
    id: "yeti-tumbler",
    name: "YETI Rambler 30oz",
    category: "kitchen",
    price: 38,
    blurb: "Keeps cold drinks cold and hot drinks hot.",
    image: "/products/yeti-tumbler.png",
  },
  {
    id: "stanley-quencher",
    name: "Stanley Quencher H2.0 40oz",
    category: "kitchen",
    price: 45,
    blurb: "Double-wall vacuum insulation. Fits in cup holders.",
    image: "/products/stanley-quencher.png",
  },
  {
    id: "instant-pot-duo",
    name: "Instant Pot Duo 7-in-1",
    category: "kitchen",
    price: 99,
    blurb: "Pressure cooker, slow cooker, rice cooker, and more.",
    image: "/products/instant-pot-duo.png",
  },
  {
    id: "ninja-air-fryer",
    name: "Ninja Air Fryer Max XL",
    category: "kitchen",
    price: 129,
    blurb: "5.5-quart capacity. Up to 75% less fat.",
    image: "/products/ninja-air-fryer.png",
  },
  {
    id: "vitamix-5200",
    name: "Vitamix 5200 Blender",
    category: "kitchen",
    price: 449,
    blurb: "Variable speed control. Aircraft-grade blades.",
    image: "/products/vitamix-5200.png",
  },
  {
    id: "hydroflask-32",
    name: "Hydro Flask 32oz Wide Mouth",
    category: "kitchen",
    price: 49,
    blurb: "TempShield insulation. Cold 24 hrs, hot 12 hrs.",
    image: "/products/hydroflask-32.png",
  },

  // ── Books ─────────────────────────────────────────────
  {
    id: "project-hail-mary",
    name: "Project Hail Mary — Andy Weir",
    category: "books",
    price: 17,
    blurb: "A lone astronaut. An impossible mission. A surprising friend.",
    image: "/products/project-hail-mary.png",
  },
  {
    id: "atomic-habits",
    name: "Atomic Habits — James Clear",
    category: "books",
    price: 14,
    blurb: "Tiny changes, remarkable results.",
    image: "/products/atomic-habits.png",
  },
  {
    id: "sapiens",
    name: "Sapiens — Yuval Noah Harari",
    category: "books",
    price: 16,
    blurb: "A brief history of humankind.",
    image: "/products/sapiens.png",
  },
  {
    id: "ddia",
    name: "Designing Data-Intensive Applications",
    category: "books",
    price: 49,
    blurb: "The big ideas behind reliable, scalable systems.",
    image: "/products/ddia.png",
  },

  // ── Beauty ────────────────────────────────────────────
  {
    id: "cerave-moisturizer",
    name: "CeraVe Moisturizing Cream 19oz",
    category: "beauty",
    price: 17,
    blurb: "Daily face & body moisturizer with hyaluronic acid.",
    image: "/products/cerave-moisturizer.png",
  },
  {
    id: "cetaphil-cleanser",
    name: "Cetaphil Gentle Skin Cleanser",
    category: "beauty",
    price: 14,
    blurb: "Soap-free, gentle on sensitive skin.",
    image: "/products/cetaphil-cleanser.png",
  },
  {
    id: "lrp-anthelios",
    name: "La Roche-Posay Anthelios SPF 60",
    category: "beauty",
    price: 36,
    blurb: "Melt-in milk sunscreen for face and body.",
    image: "/products/lrp-anthelios.png",
  },

  // ── Pets ──────────────────────────────────────────────
  {
    id: "kong-classic",
    name: "KONG Classic Dog Toy",
    category: "pets",
    price: 13,
    blurb: "The world's best dog toy. Stuff with treats.",
    image: "/products/kong-classic.png",
  },
  {
    id: "chuckit-ball",
    name: "Chuckit! Ultra Ball 4-pack",
    category: "pets",
    price: 14,
    blurb: "High-bounce, high-visibility fetch ball.",
    image: "/products/chuckit-ball.png",
  },
  {
    id: "petsafe-fountain",
    name: "PetSafe Drinkwell Fountain",
    category: "pets",
    price: 79,
    blurb: "Fresh, filtered water for cats and dogs.",
    image: "/products/petsafe-fountain.png",
  },

  // ── Sports & wellness ────────────────────────────────
  {
    id: "theragun-mini",
    name: "Therabody Theragun Mini",
    category: "wellness",
    price: 199,
    blurb: "Pocket-sized percussive therapy device.",
    image: "/products/theragun-mini.png",
  },
  {
    id: "garmin-265",
    name: "Garmin Forerunner 265",
    category: "wellness",
    price: 449,
    blurb: "AMOLED running watch with advanced training.",
    image: "/products/garmin-265.png",
  },
  {
    id: "foam-roller",
    name: "TriggerPoint GRID Foam Roller",
    category: "wellness",
    price: 39,
    blurb: "Patented multi-density EVA foam roller.",
    image: "/products/foam-roller.png",
  },
  {
    id: "resistance-bands",
    name: "Bodylastics Resistance Bands Set",
    category: "wellness",
    price: 59,
    blurb: "Anti-snap clip system. Up to 142 lbs of resistance.",
    image: "/products/resistance-bands.png",
  },
];

export function getProduct(id: string): Product | undefined {
  return products.find((p) => p.id === id);
}
